# Generated by Django 3.0.2 on 2021-01-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210124_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
