# Generated by Django 3.0.2 on 2021-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210127_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltime',
            name='travel_mode',
            field=models.CharField(choices=[('1', 'Driving'), ('2', 'Public Transit'), ('3', 'Walking')], default='Driving', max_length=200),
        ),
    ]
