# Generated by Django 3.0.2 on 2021-02-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_traveltime_travel_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltime',
            name='travel_mode',
            field=models.CharField(choices=[('driving', 'Driving'), ('transit', 'Public Transit'), ('walking', 'Walking')], default='Driving', max_length=200),
        ),
    ]
