# Generated by Django 3.1.7 on 2021-03-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210210_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltime',
            name='travel_mode',
            field=models.CharField(choices=[('driving', 'driving'), ('transit', 'public transit travel'), ('walking', 'walking')], default='Driving', max_length=200),
        ),
    ]
