# Generated by Django 3.1.7 on 2021-03-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210318_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltime',
            name='travel_mode',
            field=models.CharField(choices=[('driving', 'Driving'), ('transit', 'Public Transit'), ('walking', 'Walking')], default='Travel Mode', max_length=200),
        ),
    ]
