# Generated by Django 3.1.7 on 2021-03-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210331_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltime',
            name='travel_mode',
            field=models.CharField(choices=[('driving', 'Driving'), ('transit', 'Public Transit'), ('walking', 'Walking')], default='Driving', max_length=200),
        ),
    ]
